version: "3.2"  # optional since v1.27.0
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
    - 9393:9300
    volumes:
    - ./inputFile:/csvserver/inputdata
    environment:
    - CSVSERVER_BORDER=Orange